name: Test APK

on:
  push:
    branches:
      - test-apk
  workflow_dispatch:

permissions:
  contents: read

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle

      - name: Build
        run: ./gradlew :mobile:assembleFossBetaDebug

      - uses: actions/upload-artifact@v4
        with:
          name: openhab-foss-beta-debug
          path: mobile/build/outputs/apk/fossBeta/debug/*.apk
